[workspace]
members = [
    "svckit",
    "services/dual-writer",
    "services/dual-reader",
    "services/sstable-loader",
    "services/doctore-dash",
    "services/tui-dash",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["LuckyDrone <info@luckydrone.io>"]
edition = "2021"