{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "scylla-cluster-sync.fullname" . }}-database-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scylla-cluster-sync.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ include "scylla-cluster-sync.secretName" . }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        source-username: "{{ `{{ .sourceUsername }}` }}"
        source-password: "{{ `{{ .sourcePassword }}` }}"
        target-username: "{{ `{{ .targetUsername }}` }}"
        target-password: "{{ `{{ .targetPassword }}` }}"
  data:
    - secretKey: sourceUsername
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.sourceDatabase.remoteRef.key }}
        property: username
    - secretKey: sourcePassword
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.sourceDatabase.remoteRef.key }}
        property: password
    - secretKey: targetUsername
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.targetDatabase.remoteRef.key }}
        property: username
    - secretKey: targetPassword
      remoteRef:
        key: {{ .Values.externalSecrets.secrets.targetDatabase.remoteRef.key }}
        property: password
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scylla-cluster-sync.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scylla-cluster-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  source-username: {{ .Values.database.source.username | default "cassandra" | quote }}
  source-password: {{ .Values.database.source.password | default "CHANGE_ME" | quote }}
  target-username: {{ .Values.database.target.username | default "scylla" | quote }}
  target-password: {{ .Values.database.target.password | default "CHANGE_ME" | quote }}
{{- end }}